Create PIP-0007.md
peerplays-network/pips pull request #5
Opened 2019-10-04 01:35 UTC by atlantic-blockchain

2019-10-11 17:54 UTC, atlantic-blockchain commented
The PIP can be extended to include a mobile boilerplate, but the intention for this PIP would be for a web/desktop push. One of the reasons is due to the nature of the applications (being deployed on the peerplays blockchain) a developer certificate to be permitted in the Google Play store or the Apple Store. For example, check out section 5.3 on this site [AppleDocs](https://developer.apple.com/app-store/review/guidelines/). 

That being said, much of the functionality that will be written for this PIP, will be library based, which will make the extensibility and portability to a mobile app ( Written in VueJS or ReactJS ), much easier.

The purpose of this PIP is more to write extensible boilerplate code that works for all future application development, rather than focusing on a particular platform like mobile. Further discussion is needed for Mobile app development and more crucially, deployment before we decide to introduce a PIP to make mobile development easier.

2019-10-22 17:58 UTC, roshsyed requested changes
LGTM. Please just change the references from 0007 to 0008.

2019-10-23 01:04 UTC, atlantic-blockchain commented
> LGTM. Please just change the references from 0007 to 0008.

Done. Please proceed as normal.

2019-10-23 11:09 UTC, roshsyed approved these changes

2019-10-23 11:29 UTC, merged